### Importación de datos

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [11]:
# Unir todos los DataFrames en uno solo
import pandas as pd

df = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

In [17]:
# Crear la columna de facturación
df['Facturacion'] = df['Precio'] + df['Costo de envío']

# Facturación total general
facturacion_total = df['Facturacion'].sum()

# Facturación promedio general
facturacion_promedio = df['Facturacion'].mean()

# Facturación por vendedor
facturacion_por_vendedor = df.groupby('Vendedor')['Facturacion'].sum().sort_values(ascending=False)

# Facturación por fecha
df['Fecha de Compra'] = pd.to_datetime(df['Fecha de Compra'], dayfirst=True)
facturacion_por_fecha = df.groupby('Fecha de Compra')['Facturacion'].sum()

# Fecha con mayor facturación
fecha_max_facturacion = facturacion_por_fecha.idxmax()
monto_max_facturacion = facturacion_por_fecha.max()

# Mostrar resultados
print(f"Facturación total: {facturacion_total}")
print(f"Facturación promedio por venta: {facturacion_promedio}")
print("\nFacturación total por vendedor:")
print(facturacion_por_vendedor.reset_index().rename(columns={'Facturacion': 'Facturación total'}))

print(f"\nLa fecha con mayor facturación fue el {fecha_max_facturacion.date()} con un total de {monto_max_facturacion}")

Facturación total: 4638316200.0
Facturación promedio por venta: 491607.44038155803

Facturación total por vendedor:
           Vendedor  Facturación total
0     Felipe Santos        372652300.0
1   Izabela de León        368964800.0
2     Maria Alfonso        368282900.0
3     Juliana Costa        356385400.0
4       Pedro Gomez        330020800.0
5     Rafael Acosta        326829100.0
6    Juan Fernandez        324965300.0
7     Lucas Olivera        321683700.0
8     Camila Rivera        319351500.0
9   Beatriz Morales        318885100.0
10   Blanca Ramirez        315570800.0
11   Santiago Silva        309049100.0
12  Ángel Rodriguez        307242100.0
13  Mariana Herrera        298433300.0

La fecha con mayor facturación fue el 2021-12-06 con un total de 13700400.0

# 2. Ventas por categoría

In [18]:
ventas_categoria = df.groupby('Categoría del Producto')['Producto'].count().reset_index()
ventas_categoria.columns = ['Categoría', 'Cantidad de ventas']
ventas_categoria = ventas_categoria.sort_values(by='Cantidad de ventas', ascending=False)

print("Ventas por categoría:")
print(ventas_categoria)

Ventas por categoría:
                 Categoría  Cantidad de ventas
7                  Muebles                1886
3             Electrónicos                1772
5                 Juguetes                1290
2        Electrodomésticos                1149
1     Deportes y diversión                1113
4   Instrumentos musicales                 753
6                   Libros                 742
0  Artículos para el hogar                 730

# 3. Calificación promedio de la tienda

In [19]:
# Calificación promedio general
calificacion_promedio_general = df['Calificación'].mean()

# Calificación promedio por tienda (vendedor)
calificacion_por_vendedor = df.groupby('Vendedor')['Calificación'].mean().reset_index()
calificacion_por_vendedor.columns = ['Vendedor', 'Calificación promedio']
calificacion_por_vendedor = calificacion_por_vendedor.sort_values(by='Calificación promedio', ascending=False)

# Calificación por ciudad
calificacion_por_ciudad = df.groupby('Lugar de Compra')['Calificación'].mean().reset_index()
calificacion_por_ciudad.columns = ['Ciudad', 'Calificación promedio']
calificacion_por_ciudad = calificacion_por_ciudad.sort_values(by='Calificación promedio', ascending=False)

print(f"Calificación promedio general: {calificacion_promedio_general:.2f}")
print("\nCalificación promedio por vendedor:")
print(calificacion_por_vendedor)
print("\nCalificación promedio por ciudad:")
print(calificacion_por_ciudad)

Calificación promedio general: 4.01

Calificación promedio por vendedor:
           Vendedor  Calificación promedio
13  Ángel Rodriguez               4.134503
3     Felipe Santos               4.075606
9   Mariana Herrera               4.071646
11    Rafael Acosta               4.064000
0   Beatriz Morales               4.047692
10      Pedro Gomez               4.041221
5    Juan Fernandez               4.033141
2     Camila Rivera               4.032984
12   Santiago Silva               4.030769
1    Blanca Ramirez               3.994109
7     Lucas Olivera               3.962908
8     Maria Alfonso               3.957290
6     Juliana Costa               3.918759
4   Izabela de León               3.858871

Calificación promedio por ciudad:
           Ciudad  Calificación promedio
12          Pasto               4.148936
2          Bogotá               4.113619
17     Valledupar               4.071429
4            Cali               4.046673
5       Cartagena               4.020661
13        Pereira               4.013540
3     Bucaramanga               3.977901
6          Cúcuta               3.940860
10       Medellín               3.926534
8         Leticia               3.922535
14       Riohacha               3.895706
16         Soacha               3.894737
18  Villavicencio               3.827586
1    Barranquilla               3.803226
11          Neiva               3.800000
7         Inírida               3.642857
9       Manizales               3.634146
15    Santa Marta               3.596026
0         Armenia               3.464286

# 4. Productos más y menos vendidos

In [21]:
# Conteo de ventas por producto
ventas_producto = df['Producto'].value_counts()

producto_mas_vendido = ventas_producto.idxmax()
cantidad_mas_vendido = ventas_producto.max()
producto_menos_vendido = ventas_producto.idxmin()
cantidad_menos_vendido = ventas_producto.min()

# Valor total vendido del producto más vendido
valor_total_mas_vendido = df[df['Producto'] == producto_mas_vendido]['Facturacion'].sum()
# Vendedor con más ventas del producto más vendido
vendedor_top_producto = df[df['Producto'] == producto_mas_vendido]['Vendedor'].value_counts().idxmax()

# Lo mismo para el menos vendido
valor_total_menos_vendido = df[df['Producto'] == producto_menos_vendido]['Facturacion'].sum()
vendedor_menos_producto = df[df['Producto'] == producto_menos_vendido]['Vendedor'].value_counts().idxmax()

print(f"Producto más vendido: {producto_mas_vendido}")
print(f"Cantidad vendida: {cantidad_mas_vendido}")
print(f"Valor total facturado por este producto: {valor_total_mas_vendido}")
print(f"Vendedor con más ventas de este producto: {vendedor_top_producto}")

print("\nProducto menos vendido: ", producto_menos_vendido)
print(f"Cantidad vendida: {cantidad_menos_vendido}")
print(f"Valor total facturado por este producto: {valor_total_menos_vendido}")
print(f"Vendedor con más ventas de este producto: {vendedor_menos_producto}")

Producto más vendido: Mesa de noche
Cantidad vendida: 210
Valor total facturado por este producto: 61563500.0
Vendedor con más ventas de este producto: Santiago Silva

Producto menos vendido:  Celular ABXY
Cantidad vendida: 157
Valor total facturado por este producto: 166322800.0
Vendedor con más ventas de este producto: Lucas Olivera

# 5. Envío promedio por tienda

In [23]:
envio_promedio_vendedor = df.groupby('Vendedor')['Costo de envío'].mean().reset_index()
envio_promedio_vendedor.columns = ['Vendedor', 'Costo de envío promedio']
envio_promedio_vendedor = envio_promedio_vendedor.sort_values(by='Costo de envío promedio', ascending=False)

print("Costo de envío promedio por vendedor:")
print(envio_promedio_vendedor)

Costo de envío promedio por vendedor:
           Vendedor  Costo de envío promedio
8     Maria Alfonso             27375.699558
3     Felipe Santos             26899.144080
6     Juliana Costa             26618.463811
11    Rafael Acosta             26458.880000
10      Pedro Gomez             25450.229008
4   Izabela de León             25030.107527
0   Beatriz Morales             24906.923077
2     Camila Rivera             24238.830585
7     Lucas Olivera             24154.451039
12   Santiago Silva             24047.538462
5    Juan Fernandez             23635.734870
1    Blanca Ramirez             23540.795287
9   Mariana Herrera             23065.091463
13  Ángel Rodriguez             22831.725146

# 6. Informe Final

In [26]:
tienda1 = pd.read_csv(url)
tienda1["Tienda"] = "Tienda 1"

tienda2 = pd.read_csv(url2)
tienda2["Tienda"] = "Tienda 2"

tienda3 = pd.read_csv(url3)
tienda3["Tienda"] = "Tienda 3"

tienda4 = pd.read_csv(url4)
tienda4["Tienda"] = "Tienda 4"

# Unimos todos los datos en un solo DataFrame
df = pd.concat([tienda1, tienda2, tienda3, tienda4], ignore_index=True)

In [28]:
# Agregar columna de facturación
df['Facturacion'] = df['Precio'] + df['Costo de envío']

# Agrupamos por Tienda real (no por vendedor)
resumen_tiendas = df.groupby('Tienda').agg({
    'Precio': 'sum',
    'Costo de envío': 'sum',
    'Facturacion': 'sum',
    'Producto': 'count',
    'Calificación': 'mean'
}).reset_index()

resumen_tiendas.columns = ['Tienda', 'Total en ventas', 'Total en envíos', 'Facturación total', 'Cantidad de ventas', 'Calificación promedio']
resumen_tiendas['Lucro estimado'] = resumen_tiendas['Total en ventas']

# Ordenamos por menor lucro
resumen_ordenado = resumen_tiendas.sort_values(by='Lucro estimado')

# Seleccionamos la tienda con menos lucro
peor_tienda = resumen_ordenado.iloc[0]

print("🔍 Informe de evaluación por tienda\n")
print("Resumen general por tienda:")
resumen_ordenado_format = resumen_ordenado.copy()
cols_a_formatear = ['Total en ventas', 'Total en envíos', 'Facturación total', 'Cantidad de ventas', 'Lucro estimado']

for col in cols_a_formatear:
    resumen_ordenado_format[col] = resumen_ordenado_format[col].apply(lambda x: f"${x:,.0f}")

resumen_ordenado_format['Calificación promedio'] = resumen_ordenado_format['Calificación promedio'].round(2)

display(resumen_ordenado_format)

print("\n📉 Tienda con menor lucro estimado:")
print(f"- {peor_tienda['Tienda']}")
print(f"- Lucro estimado: ${peor_tienda['Lucro estimado']:,.0f}")
print(f"- Cantidad de ventas: {int(peor_tienda['Cantidad de ventas'])}")
print(f"- Calificación promedio: {peor_tienda['Calificación promedio']:.2f}")
print(f"- Facturación total (incluyendo envíos): ${peor_tienda['Facturación total']:,.0f}")

print("\n📌 Recomendación:")
print(f"La {peor_tienda['Tienda']} es la menos rentable según las métricas de ventas, lucro y calificación.")
print("Se sugiere evaluar si esta tienda debe mantenerse operativa, mejorar su estrategia comercial o considerar su cierre.")

🔍 Informe de evaluación por tienda

Resumen general por tienda:

,Tienda,Total en ventas,Total en envíos,Facturación total,Cantidad de ventas,Calificación promedio,Lucro estimado
3,Tienda 4,"$1,038,375,700","$55,317,400","$1,093,693,100","$2,358",4.00,"$1,038,375,700"
2,Tienda 3,"$1,098,019,600","$58,516,600","$1,156,536,200","$2,359",4.05,"$1,098,019,600"
1,Tienda 2,"$1,116,343,500","$59,485,100","$1,175,828,600","$2,359",4.04,"$1,116,343,500"
0,Tienda 1,"$1,150,880,400","$61,377,900","$1,212,258,300","$2,359",3.98,"$1,150,880,400"

📉 Tienda con menor lucro estimado:
- Tienda 4
- Lucro estimado: $1,038,375,700
- Cantidad de ventas: 2358
- Calificación promedio: 4.00
- Facturación total (incluyendo envíos): $1,093,693,100

📌 Recomendación:
La Tienda 4 es la menos rentable según las métricas de ventas, lucro y calificación.
Se sugiere evaluar si esta tienda debe mantenerse operativa, mejorar su estrategia comercial o considerar su cierre.